# https://taskfile.dev

version: '3'

vars:
  DATE: $(date -u -j -f %s $(git show -s --format=%ct) +%Y%m%d%H%M)
  GITSHA: $(git rev-parse --short HEAD)

tasks:
  default:
    cmds:
    - task: build-push
  build-push:
    cmds:
      - "docker buildx build --platform linux/amd64,linux/arm64 --push -t ghcr.io/willnewby/kshell:{{.DATE}}-{{.GITSHA}} -t ghcr.io/willnewby/kshell:latest ."
